# -*- coding: utf-8 -*-
"""Task06_2025.ipynb

Automatically generated by Colab.
"""

# !pip install rdflib
import urllib.request
url = 'https://raw.githubusercontent.com/FacultadInformatica-LinkedData/Curso2025-2026/refs/heads/master/Assignment4/course_materials/python/validation.py'
urllib.request.urlretrieve(url, 'validation.py')
github_storage = "https://raw.githubusercontent.com/FacultadInformatica-LinkedData/Curso2025-2026/master/Assignment4/course_materials"

"""Import RDFLib main methods"""

from rdflib import Graph, Namespace, Literal, XSD
from rdflib.namespace import RDF, RDFS
from validation import Report
g = Graph()
g.namespace_manager.bind('ns', Namespace("http://somewhere#"), override=False)
r = Report()

"""Create a new class named Researcher"""

ns = Namespace("http://mydomain.org#")
g.add((ns.Researcher, RDF.type, RDFS.Class))
for s, p, o in g:
  print(s,p,o)

"""**Task 6.0: Create new prefixes for ontology and person**"""

ontology = Namespace("http://oeg.fi.upm.es/def/people#")
person = Namespace("http://oeg.fi.upm.es/resource/person/")
g.namespace_manager.bind("ontology", ontology)
g.namespace_manager.bind("person", person)

"""**TASK 6.1: Taxonomy**"""

Person = ontology.Person
Professor = ontology.Professor
AssociateProfessor = ontology.AssociateProfessor
InterimAssociateProfessor = ontology.InterimAssociateProfessor
FullProfessor = ontology.FullProfessor

classes = [Person, Professor, AssociateProfessor, InterimAssociateProfessor, FullProfessor]

for c in classes:
  g.add((c, RDF.type, RDFS.Class))
  g.add((c, RDFS.label, Literal(c.split("#")[-1], datatype=XSD.string)))

g.add((Professor, RDFS.subClassOf, Person))
g.add((AssociateProfessor, RDFS.subClassOf, Professor))
g.add((InterimAssociateProfessor, RDFS.subClassOf, AssociateProfessor))
g.add((FullProfessor, RDFS.subClassOf, Professor))

# Visualize
for s, p, o in g:
  print(s,p,o)

# Validation
r.validate_task_06_01(g)

"""**TASK 6.2: Properties**"""

hasColleague = ontology.hasColleague
hasName = ontology.hasName
hasHomePage = ontology.hasHomePage

g.add((hasColleague, RDF.type, RDF.Property))
g.add((hasColleague, RDFS.domain, Person))
g.add((hasColleague, RDFS.range, Person))
g.add((hasColleague, RDFS.label, Literal("hasColleague", datatype=XSD.string)))

g.add((hasName, RDF.type, RDF.Property))
g.add((hasName, RDFS.domain, Person))
g.add((hasName, RDFS.range, RDFS.Literal))
g.add((hasName, RDFS.label, Literal("hasName", datatype=XSD.string)))

g.add((hasHomePage, RDF.type, RDF.Property))
g.add((hasHomePage, RDFS.domain, FullProfessor))
g.add((hasHomePage, RDFS.range, RDFS.Literal))
g.add((hasHomePage, RDFS.label, Literal("hasHomePage", datatype=XSD.string)))

# Visualize
for s, p, o in g:
  print(s,p,o)

r.validate_task_06_02(g)

"""**TASK 6.3: Individuals**"""

Oscar = person["Oscar"]
Asun  = person["Asun"]
Raul  = person["Raul"]

g.add((Oscar, RDF.type, Professor))
g.add((Oscar, RDFS.label, Literal("Oscar", datatype=XSD.string)))
g.add((Oscar, hasName, Literal("Óscar Corcho García", datatype=XSD.string)))
g.add((Oscar, hasColleague, Asun))

g.add((Asun, RDF.type, AssociateProfessor))
g.add((Asun, RDFS.label, Literal("Asun", datatype=XSD.string)))
g.add((Asun, hasHomePage, Literal("http://oeg.fi.upm.es/", datatype=XSD.string)))
g.add((Asun, hasColleague, Raul))

g.add((Raul, RDF.type, InterimAssociateProfessor))
g.add((Raul, RDFS.label, Literal("Raul", datatype=XSD.string)))
g.add((Raul, hasColleague, Oscar))

# Visualize
for s, p, o in g:
  print(s,p,o)

r.validate_task_06_03(g)

"""**TASK 6.4: VCARD + FOAF**"""

VCARD = Namespace("http://www.w3.org/2001/vcard-rdf/3.0/")
FOAF = Namespace("http://xmlns.com/foaf/0.1/")

g.add((Oscar, VCARD.Given, Literal("Oscar", datatype=XSD.string)))
g.add((Oscar, VCARD.Family, Literal("Corcho", datatype=XSD.string)))
g.add((Oscar, FOAF.email, Literal("oscar@upm.es", datatype=XSD.string)))

# Visualize
for s, p, o in g:
  print(s,p,o)

r.validate_task_06_04(g)
r.save_report("_Task_06")
