# -*- coding: utf-8 -*-
"""Task07_2025.ipynb

Automatically generated by Colab.
"""

# !pip install rdflib
import urllib.request
url = 'https://raw.githubusercontent.com/FacultadInformatica-LinkedData/Curso2025-2026/refs/heads/master/Assignment4/course_materials/python/validation.py'
urllib.request.urlretrieve(url, 'validation.py')
github_storage = "https://raw.githubusercontent.com/FacultadInformatica-LinkedData/Curso2025-2026/master/Assignment4/course_materials"

from validation import Report

"""Read RDF"""

from rdflib import Graph, Namespace, Literal
from rdflib.namespace import RDF, RDFS
from rdflib.plugins.sparql import prepareQuery

g = Graph()
g.namespace_manager.bind('ns', Namespace("http://somewhere#"), override=False)
g.parse(github_storage+"/rdf/data06.ttl", format="TTL")
report = Report()

"""TASK 7.1a"""

result = []
for c in set(g.subjects(RDF.type, RDFS.Class)):
    sc = g.value(subject=c, predicate=RDFS.subClassOf)
    result.append((c, sc))

for r in result:
    print(r)

report.validate_07_1a(result)

"""TASK 7.1b"""

query = """
SELECT DISTINCT ?c ?sc WHERE {
  ?c a rdfs:Class .
  OPTIONAL { ?c rdfs:subClassOf ?sc . }
}
"""

for r in g.query(query):
    print(r.c, r.sc)

report.validate_07_1b(query, g)

"""TASK 7.2a"""

ns = Namespace("http://oeg.fi.upm.es/def/people#")

classes = {ns.Person} | set(
    g.transitive_subjects(RDFS.subClassOf, ns.Person)
)

individuals = sorted(
    {i for c in classes for i in g.subjects(RDF.type, c)},
    key=str
)

for i in individuals:
    print(i)

report.validate_07_02a(individuals)

"""TASK 7.2b"""

query = prepareQuery("""
SELECT ?ind WHERE {
  ?ind rdf:type ?c .
  ?c rdfs:subClassOf* ns:Person .
}
""", initNs={"ns": ns, "rdf": RDF, "rdfs": RDFS})

for r in g.query(query):
    print(r.ind)

report.validate_07_02b(g, query)

"""TASK 7.3"""

query = prepareQuery("""
SELECT ?name ?type WHERE {
  ?x ns:knows ns:Rocky .
  ?x rdf:type ?type .
  ?x rdfs:label ?name .
}
""", initNs={"ns": ns, "rdf": RDF, "rdfs": RDFS})

for r in g.query(query):
  print(r.name, r.type)

report.validate_07_03(g, query)

"""TASK 7.4"""

query = prepareQuery("""
SELECT DISTINCT ?name WHERE {
 {
    ?x rdfs:label ?name .
    ?x ns:hasColleague ?y .
 }
 UNION
 {
    ?x rdfs:label ?name .
    ?x ns:hasColleague ?y .
    ?y ns:hasColleague ?z .
 }
}
""", initNs={"ns": ns, "rdfs": RDFS})

for r in g.query(query):
  print(r.name)

report.validate_07_04(g, query)
report.save_report("_Task_07")
